server:
  port: 8080

spring:
  application:
    name: ms-vidasalud-bff

azure:
  issuer: https://login.microsoftonline.com/b474f3ba-4718-40c4-90eb-000db1255fdd/v2.0
  audience: 213b4c6d-59e8-44e4-a319-63b38eef4c6e

services:
  appointments-url: http://localhost:8081
  catalog-url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health